# Generated by Django 5.0.7 on 2024-08-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(default='None', max_length=256)),
                ('text', models.CharField(default='None', max_length=512)),
            ],
        ),
    ]
